### ISSUE TITLE
Jamf Protect protocol check always returns error when using WSS/MQTT plan

### ISSUE THREAD

**Issue by kiyo9999** [txhaflaire/JamfCheck#12]
Please forgive me if I'm being rude as I'm new to Github.
When I apply a Jamf Protect plan that uses the wss/mqtt protocol, JamfCheck always shows an error, even though the Mac can communicate with Jamf Protect Cloud via wss/mqtt without any problems.
Please see the attached files which contain
1, output of "protectctl info -v" which shows that the Mac can connect to the Protect Cloud via wss/mqtt.
2, JamfCheck log which says "Jamf Protect configuration does not have a valid communication protocol".

I would be grateful if you could respond to this report.

[jamfchecklog.txt](https://github.com/user-attachments/files/16176043/jamfchecklog.txt)
[protectctl.txt](https://github.com/user-attachments/files/16176057/protectctl.txt)
<img width="911" alt="screenshot" src="https://github.com/txhaflaire/JamfCheck/assets/14288612/b90a735f-03aa-46bc-b03f-3a1afc56f734">

**Comment by txhaflaire** [comment]
Hi @kiyo9999 - thanks for reporting this in, you are right, i missed this return value.

Will be resolved in next release.

**Comment by kiyo9999** [comment]
Hi !
Thank you for your prompt investigation. Looking forward to the next release!

**Comment by txhaflaire** [comment]
Resolved in v2.1.1
