### ISSUE TITLE
Firewall disabled

### ISSUE THREAD

**Issue by DS13377** [txhaflaire/JamfCheck#14]
JamfCheck shows that the firewall is disabled even though it is enabled. The firewall is controlled by a configuration profile through JamfPro. The issue exists on all our devices and has been present for several versions.

**Comment by mjabroux** [comment]
Confirm the issue on Mac OS 15/ M1
<img width="933" alt="Screenshot 2024-10-03 at 17 12 44" src="https://github.com/user-attachments/assets/bd09599f-b9e6-4e1c-815c-9a844cbdfc67">

**Comment by DS13377** [comment]
Hi,

same issue on macOS 15 / M2.
No M1 available.



Greetings



Von:    "Mikhael Jabroux" ***@***.***>
An:     "txhaflaire/JamfCheck" ***@***.***>
Kopie:  "DS13377" ***@***.***>, "Author" 
***@***.***>
Datum:  03.10.2024 17:13
Betreff:        Re: [txhaflaire/JamfCheck] Firewall disabled (Issue #14)



Confirm the issue on Mac OS 15/ M1
Screenshot.2024-10-03.at.17.12.44.png (view on web)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Der Schutz Ihrer personenbezogenen Daten ist der Stadt Dortmund ein 
wichtiges Anliegen. Weitere Informationen finden Sie unter folgendem Link: 
http://www.dortmund.de/datenschutz.
Unverschlüsselte E-Mails können auf allen Internetstrecken unbefugt 
mitgelesen/verändert werden.

Bitte denken Sie an die Umwelt, bevor Sie diese E-Mail ausdrucken. Pro 
Blatt sparen Sie durchschnittlich 15g Holz, 260ml Wasser, 0,05kWh Strom 
und 5g CO2.

**Comment by txhaflaire** [comment]
Resolved in v2.2.0

**Comment by DS13377** [comment]
Hi,

after the fix in v2.2.0 the same issue occured in macOS 15.1.1
JamfCheck shows that the firewall is disabled even though it is enabled.
![Bildschirmfoto 2024-11-27 um 06 28 41](https://github.com/user-attachments/assets/860d0b4f-af3c-41e0-a47d-d4a7e249049f)

Greetings
DS1337
