### ISSUE TITLE
Ability to hide buttons for the JAMF tools not setup on device/in organisation

### ISSUE THREAD

**Issue by mjabroux** [txhaflaire/JamfCheck#15]
Hello,

Thanks for the hard work! Loving this tool so far!
Would it be possible to pick and choose/remove the JAMF tools that we do not use in our organisation?
(i.e.: if we do not use Jamf protect/Jamf connect, have the ability to hide the buttons)

<img width="154" alt="Screenshot 2024-10-03 at 17 13 41" src="https://github.com/user-attachments/assets/faacba17-8bcb-4351-9573-4df5cb854c69">

**Comment by txhaflaire** [comment]
Hey!

Thats already possible today, although i have not documented it.

As example deploy this config using Jamf

`com.txhaflaire.JamfCheck`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>jamfConnectEnabled</key>
	<true/>
	<key>jamfProEnabled</key>
	<true/>
	<key>jamfProtectEnabled</key>
	<false/>
</dict>
</plist>
```

**Comment by mjabroux** [comment]
Awesome! Thanks
