### ISSUE TITLE
Jamf Agent

### ISSUE THREAD

**Issue by nlecchi** [txhaflaire/JamfCheck#5]
The Jamf Agent process is sometimes found to be inactive.  What should I check for?
<img width="429" alt="Jamf Agent" src="https://github.com/txhaflaire/JamfCheck/assets/82441389/e930a948-8a20-40a4-b212-331ed9ae5152">

**Comment by psaintemarie** [comment]
@nlecchi The JamfAgent has been deprecated since Jamf Pro 10.31.0
See https://docs.jamf.com/10.31.0/jamf-pro/release-notes/Deprecations_and_Removals.html

**Comment by psaintemarie** [comment]
This issue should be renamed as: "Show Jamf Agent status only when Jamf Pro version is lower than 10.31"

**Comment by txhaflaire** [comment]
Thanks both for catching this - will be adressed in next release, i might drop this check as Jamf pro 10.31 is not supported anymore anyway.

**Comment by HowardGMac** [comment]
I would suggest that the UI use the JAMF Binary version information to selectively hide or show this item.  If the version is 10.31 or older show it.  If greater, hide it.    Just in case someone is still using the applicable version for some reason.
