### ISSUE TITLE
Adding Jamf Connect License Status

### ISSUE THREAD

**Issue by dornoam41** [txhaflaire/JamfCheck#9]

**Comment by dornoam41** [comment]
Would it be possible to include if Jamf connect is licensed?

**Comment by txhaflaire** [comment]
@dornoam41 definitly - should be able to decode and show the state. Will consider adding this in next release

**Comment by txhaflaire** [comment]
@dornoam41 

Would this be something that's helpful?

<img width="520" alt="image" src="https://github.com/txhaflaire/JamfCheck/assets/26306960/2c1e88b5-43f5-4e68-b0a2-846b72489f1a">

Also - when it's expired the status icons changes accordingly.

<img width="517" alt="image" src="https://github.com/txhaflaire/JamfCheck/assets/26306960/b2725567-3ad3-431c-bed2-d10f16f57082">

**Comment by dornoam41** [comment]
Yep, looks good, thanks for adding that 👍

**Comment by txhaflaire** [comment]
Added in version 2.1.0
